version: 2

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/cloudsprints/sprintctl/cmd.Version={{.Version}}
      - -X github.com/cloudsprints/sprintctl/internal/auth.GraderSecret={{.Env.GRADER_SECRET}}
archives:
  - format: binary
# brews:
#   - tap:
#     owner: cloudsprints
#     name: sprintctl-tap 
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
